### ISSUE TITLE
New Function Addition Request

### ISSUE THREAD

**Issue by brichard1638** [william-swl/baizer#22]
I have been working with, and analyzing data through the use of Histograms lately. As I was working with the histogram object, I realized that there is no easy and quick way to identify the observations represented by the bins in a Histogram. Wouldn't it be nice if a function could be created that extracted all the observations from a variable based on the bins generated through a Histogram?

**New Function Output:**
The output would be a data frame object with 4 variables: the first variable would be a row representing the index numbers extracted from the original numeric variable passed to the hist function in the graphics package.  The second variable would be the actual numeric value; the third variable would be the bin number and the fourth variable would be the bin range. For example, where price is the target variable used to generate a Histogram and the first bin of the histogram has been returned:

indx |  price  | bin  | rng
133  |  9.592  |    1  |    0-10
386  |  8.792  |    1  |    0-10
405  |  8.792  |    1  |    0-10
409  |  8.792  |    1   |   0-10

Based on its histogrammatic disaggregation, each value would be captured from the target variable relative to its index position, category, bin, and range.

**New Function Name:**
The proposed name for this function could be **hist_obs_bins**.

**Arguments:**
There are a few ways this function could be constructed. Perhaps the easiest way would be to pass nothing more than two arguments consisting of a data frame object and the target variable used to histogrammically parse.

**Function Construction Recommendation:**
The function should include a process whereby an object of class histogram is created so that the breaks element can be extracted. Both the bin and range data can be discerned from this data point. Using a for loop, the subset function could be used to extract both the index position and the target variable's value. For example, extracting the index positions and values from the first bin where the breaks are 0 and 10 might return the following results:

subset(d.pizza, price > 0 & price < 10, select = price)
        price
133 | 9.592
386 | 8.792
405 | 8.792
409 | 8.792

An example of a vector of breaks might look like the following where hist.pizza.price is an object of class histogram:
hist.pizza.price$breaks
 [1]   0  10  20  30  40  50  60  70  80  90 100 110 120 130 140

**Comment by william-swl** [comment]
It's great. I have added a function named `hist_bins`.

I think it's awesome if this function can work on any numeric vector, especially you can fetch a vector easily by `dplyr::pull(df, value_col, id_col)`.
What's more, you don't need any more information in the dataframe except these two columns, so maybe using the whole dataframe as input is unnecessary.

Please try it out, and let me know if there is any trouble.

After all, thanks for your feedback my friend.

```r
vector <- dplyr::pull(mini_diamond, price, id)

hist_bins(vector, bins = 20)
#> # A tibble: 100 × 5
#>    id    value  start    end   bin
#>    <chr> <int>  <dbl>  <dbl> <int>
#>  1 id-1   3027  2218.  3097.     3
#>  2 id-2  11746 11000. 11879.    13
#>  3 id-3   2029  1340.  2218.     2
#>  4 id-4   9452  9244  10122.    11
#>  5 id-5   2498  2218.  3097.     3
#>  6 id-6  14080 13635  14513.    16
#>  7 id-7    752   462   1340.     1
#>  8 id-8   1029   462   1340.     1
#>  9 id-9   5590  4853   5731.     6
#> 10 id-10  1691  1340.  2218.     2
#> # … with 90 more rows
```

**Comment by brichard1638** [comment]
William:::

Thank you for your prompt response to my suggestion. I have tested the hist_bins function that you provided. Certainly, from a pure binning perspective, this function demonstrates one method by which to bin data.

However, I was hoping that instead of binning data purely from the number of bins passed in the function, that the binning would initially start from the binning provided by the hist function found in the graphics package. This is why I alluded to that function as being a part of the data process. The idea was to be able to extend the hist function by returning a dataset that captured the actual values as they are related to their corresponding bins.

Having said that, there are many packages in R that extend the concept of binning using a variety of statistically-driven ideas, principal among them is the optbin package which I use anytime I need to bin data which requires a statistically defined justification for binning.

I do like that you added a **start** and **end** variable to the output. That is really good.

So, if I can persuade you to either modify or add a new function that would conduct binning based on the results provided by the hist function, that would be great! Combining both of the data output ideas generated between both of our interpretations of this process, the output might look like the following:

indx | price |   start   |   end   | bin |   rng
133 | 9.592 |  8.792  |  9.592  |   1    | 0-10
386 | 8.792 |  8.792  |  9.592  |   1    | 0-10
405 | 8.792 |  8.792  |  9.592  |   1    | 0-10
409 | 8.792 |  8.792  |  9.592  |   1    | 0-10

The key here is the starting point which is the data captured from the hist function for determining the bins and their breaks. The challenge after that is to map the index, bin, range, and values together in a single data object.

**Comment by brichard1638** [comment]
William:::

Hey! I hope all is well with you. I provided a response on your GitHub account.

Thanks!

Brice
________________________________

**Comment by william-swl** [comment]
I add an argument `breaks` to function `hist_bins()`, which allows you to do this:

```
> data <- dplyr::pull(mini_diamond, price, id)
> h <- hist(data)
> res <- hist_bins(data, breaks=h$breaks)
> res
# A tibble: 100 × 5
   id    value start   end   bin
   <chr> <int> <dbl> <dbl> <int>
 1 id-1   3027  2000  4000     2
 2 id-2  11746 10000 12000     6
 3 id-3   2029  2000  4000     2
 4 id-4   9452  8000 10000     5
 5 id-5   2498  2000  4000     2
 6 id-6  14080 14000 16000     8
 7 id-7    752     0  2000     1
 8 id-8   1029     0  2000     1
 9 id-9   5590  4000  6000     3
10 id-10  1691     0  2000     1
# … with 90 more rows
# ℹ Use `print(n = ...)` to see more rows
```

Now you can use `res %>% dplyr::filter(bin==2)` to fetch the values in the second bin on `hist()` plot.

**Comment by brichard1638** [comment]
I've tested the most recent version of the hist_bins function captured in v0.4.0. It is awesome! In only 3 lines of code you can extract all the values from a numerical variable that has been processed through R's native hist function capturing the id, value, bin start and end, and the bin number. Excellent!

If there is any feedback I have on this wonderful function it's that the pull function used to create a Named Vector, in my opinion, somewhat limits the utility of the function. That is to say, what if the row numbers were what needed to be passed instead of an actual variable? One would have to independently create (duplicate) the row numbers as a separate variable in the dataset. It's not a big deal but it certainly would be a little easier if the row numbers could be passed directly to pull. I experimented briefly with this possibility but was unable to pass row numbers directly.

Nonetheless, the function is great as it stands, and the ability to use such an economy of code to get the quality and order of data returned is an amazing function-add to the baizer package. I look forward to the next version of baizer on CRAN!

**Comment by william-swl** [comment]
I guess you work with a `data.frame` object instead of a `tibble` object, which has a stand alone rowname more than columns.

If then, you can use `df %>% tibble::as_tibble(rownames='rowid')` to create a `tibble` object including a column named `rowid`.

If you already work with a `tibble` object and need to know the rowid in each bin, I think it's worthwhile to save this information into a column. e.g. `df %>% dplyr::mutate(rowid=1:n())`

**Comment by william-swl** [comment]
Please let me know if I missed something.

Preparing on the next CRAN release!!

**Comment by brichard1638** [comment]
Yes!

I do work more with data frames than tibble objects although I believe the standard in R is tibble relative to structured spread-sheet like data objects.

When working with data frames, you do have to go through the extra step of creating a unique data field, which is fine. I do like the naming convention you offered at id-1, id-2, etc.  It makes the process absolutely clear as to how the records are defined.

So, that's why I didn't offer a counterargument to that idea. It's robust and it just works. Do publish!
