### ISSUE TITLE
New Function Proposal: Generate a Dataset by Solution Category (Concept)

### ISSUE THREAD

**Issue by brichard1638** [william-swl/baizer#24]
There is an obscure paradox that emerges when working with datasets in R. While there is at least one dataset available in almost every R package on CRAN, it is rather difficult to find the right dataset to accommodate the right set of functions being used to better understand data. This is especially true when moving to convert data in R to a plot. In many cases, the right data types along with a particular data structure is required before a plot can be generated.

For example, when learning how to apply a compelling bar plot, what kind of dataset should be used? What is an appropriate dataset to use when working with natural language processing? How about regression modeling? Finding the right dataset to support targeted learning of particular functions in R can be surprisingly difficult. To accentuate the challenge, many of the dataset examples provided in R packages are overly simplistic, which can inadvertently thwart the learning process.

This solution proposes to solve this problem by introducing a new way of thinking about R datasets. This idea proposes to create a dataset based on the kind of general problem it solves. A proposed function, its structure, and a brief explanation of its component parts are provided.

**Function Name: getDataset**
**Function Structure:    getDataset(type = "randomized", sets = 1, asDF = TRUE)**
*NOTE: The preferred functional implementation of getDataset should be to call the function without an object name designation. For example **getDataset(type = "NLPwords", sets = 2)** is acceptable not **dfobj = getDataset(type = "NLPwords", sets = 2).** The problem with allowing an object designation occurs when the user passes a value greater than 1 in the sets argument. How would that configuration be handled? For purposes of continuity, it is recommended that passing a naming object should return a null value even if the sets value maintains a value of 1. This result encourages the user to correctly configure the getDataset function. Default data object names can be independently modified by the user subsequent to their creation.

**Argument TYPE Description: The type argument provides a string list of a set of general categories into which the dataset falls. Type options include the following: class for classification, regression, binqual for qualitative binning, binquant for quantitative binning, binmat for a binary matrix, randomized, which generates a random (classic) generated dataset each time the function is executed with this type, NLPfruit for an NLP dataset called fruit, NLPsent for an NLP-based dataset that captures sentences, NLPwords, which is a word-based dataset, ts for time series, and finally, summary, which captures an aggregated dataset.**

**Argument TYPE Total Options: 11**

**Argument SETS Description: This argument determines the number of datasets that are generated under the selected type. Options include 1, 2, or 3. Values of 2 or 3 will generate different datasets with different structures but still fall under the same category selected by the type argument.**

**Argument ASDF Description: This argument passes a binary value of either TRUE or FALSE. A True value returns either a dataframe or a tibble structure as the dataset(s), and False returns a list object containing the following elements:**
- The name of the R package where the dataset originates
- The name of the original dataset
- The dataset object

**Because the dataset object is being repurposed within a new function, it is proposed that the name of the dataset object be defined by the following naming convention, irrespective of the asDF boolean value:**
- An abbreviated version of the type + df + numeric value of either 1, 2, or 3 consistent with the sets value
- Naming convention protocol examples: classDF1, regDF1, binqualDF1, binquantDF1, binmatDF1, randDF1, nlpfruitDF1, nlpsentDF1, nlpwordsDF1, tsDF1, sumDF1

**NOTE: Converting time-series objects to a formalized dataset will be a subjective call and could be captured either as a class ts or as a class dataframe or tibble. Perhaps another optional argument may be considered in the getDataset function to determine how time-series objects are returned. It should be noted that many of the plotting functions provided in R require time-series objects to be of class ts to be plotted. The same issue applies to the binmat output. Do you generate a matrix or a dataframe/tibble object?**

**Comment by william-swl** [comment]
I think it's amazing if those datasets (or the functions to generate them) can be obtained in a single dataset package, while the aims of `baizer` are not to provide datasets, but to include useful data operation functions.

After all, thanks for your suggestions!
