### ISSUE TITLE
New Function Proposal: Generate a Dataset by Solution Category (Code Ideas)

### ISSUE THREAD

**Issue by brichard1638** [william-swl/baizer#25]
This issue is a continuation of the getDataset function proposal provided in the issue titled, **New Function Proposal: Generate a Dataset by Solution Category (Concept).**

This issue provision provides some recommendations for the datasets supporting the TYPE argument earlier described.
- class - data(iris), library(modeldata), data(credit_data), library(ExamPAData), data(auto_claim)
- regression - library(DAAG), data(milk), library(BSDA), data(Tablrock)
- binqual - library(vcdExtra), data(AirCrash), library(vcd), data(Arthritis)
- binquant - library(Stat2Data), data(HorsePrices), library(DescTools), data(d.pizza), library(tigerstats), data(tips)
- binmat - Generate a random binary matrix from a Bernoulli graph distribution; library(sna) using the rgraph function; another function that can be used is the rlbmat function contained in the cba package; this function generates a simulated binary matrix with encoded binary pattern sets containing TRUE or FALSE values; these values would need to be further converted into a binary matrix of 0s and 1s. The output is extraordinary because it generates not only a binary matrix, but one with discernible patterns (when plotted)

randomized - The code used to generate randomized datasets can be expedited by applying existing R functions originating from different R packages. In this space, there are (3) powerful functions that can be used to facilitate the creation of randomized datasets. The R packages and the functions originating therein are listed below:
- library(div) - function **div_fake_team**
- library(fabricatr) - function **fabricate** (used in conjunction with the add_level and cross_levels functions, this function can be used to simulate hierarchical datasets, which could be captured as a separate type)
- library(explore) - function **create_data_app**
**NOTE: Some of these functions provide more complex methods by which to generate randomized datasets. More information can be provided by way of code to support this dataset type if needed.**

NLPfruit, NLPsent, and NLPwords all derive from the stringr package. Each object is a vector that would need to be converted into a formalized dataset with optionally encoded additional data:
- data(fruit)
- data(sentences)
- data(words)

Time-series dataset creation
Since time-series datasets are configured a little different as a separate class in R, creating them is not intuitive in terms of the functions used. The classic function used to generate time-series datasets is ts, originating from the stats package. However, there is another function that can also be used that expands on the ts function:
- library(tstools) - function **generate_random_ts**
- Existing time-series datasets: data(airmiles) found in the datasets package
- library(TSA) - contains several time-series datasets including but not limited to data(beersales), data(color), data(hare), data(gold), data(tempdub)

To generate the summary-based dataset, certain functions are better to use than others. The best functions I've found for creating variable-based summary datasets are as follows:
- library(guf); function **aggro** - This function is preferred over the stats function aggregate as it successfully processes missing values as a separate group category, where the aggregate function does not.
- library(guf); function **count** - This if one of the most versatile functions I've found for use in slicing and dicing data for the purposes of generating summaries

**Comment by william-swl** [comment]
I think it's amazing if those datasets (or the functions to generate them) can be obtained in a single dataset package, while the aims of `baizer` are not to provide datasets, but to include useful data operation functions.

After all, thanks for your suggestions!
