### ISSUE TITLE
New Function Proposal: Download a Random Image from the Internet

### ISSUE THREAD

**Issue by brichard1638** [william-swl/baizer#26]
The idea for this function is to generate a programmatic capability that can be used to download one or more random images from the internet. Using the www.unsplash.com website, provide a one-step function to achieve this objective.

Proposed Function Name & Structure: **genImage(fp = "~/images"), cat = "nature", cnt = 1)**
- fp = File path and name of the directory to which the image(s) will be stored
- cat = The general category comprising the image type (see NOTE4 at the bottom)
- cnt = The total number of images to generate

NOTE1: An additional argument could be provided called ext that determines which image type extension to generate, For example, ext = "jpg" or ext = "png", etc. Extra code may be required to implement this functionality.

NOTE2: File size can also be added as an argument called size, or independently as two separate arguments called len and wid. Values would programmatically replace those passed in the url argument of the download.file function.

The following code is designed to provide a framework for a functional conversion:

ACQUIRE ONE RANDOM IMAGE FILE
The first step is to download a random image to a pre-established folder in the MyDocuments folder called 'images:'
``
dir.create(path = "~/images")
``
``
download.file(url = "https://source.unsplash.com/random/800x800/?nature&1", destfile = "~/images/img1.jpg", mode = 'wb')
``

The ~/ character combination represents an abbreviated file path to a user's My Documents folder. Any file path to which a sub-folder reference is made deeper than the My Documents folder must be manually included in the file path string.

ACQUIRE MULTIPLE RANDOM IMAGE FILES
To download a user-selected number of random image files (in this example 10), apply the following code:
``
library(wakefield)
``
``
for(i in 1:10) {
``
``
  download.file(url = paste0("https://source.unsplash.com/random/500x500/?nature&", i), destfile = paste0("~/images/", string(1, length = 5), ".jpg"), mode = 'wb')
``
``
  Sys.sleep(1)
}
``

NOTE1: In the code above, (10) random images are downloaded and saved to a sub-folder called 'images.'

NOTE2: The image file size can be easily modified by changing the numeric value references contained in the url.

NOTE3: It is possible that one or more images will be duplicated. The Sys.sleep function reduces this possibility by decelerating the speed at which the code executes. This minimizes the prospect of downloading a duplicate image. If the R code executes too fast, images will be duplicated as the algorithm executes before the website can regenerate a new image.

NOTE4: Key words used to generate images can be found at the top of the www.unsplash.com page. These key words can be used to replace the 'nature' keyword provided in the download.file function. However, it should be noted that the images returned are inconsistent and do not always match the key word provided. Consequently, the key word that returns the most consistently applicable images is 'nature.'

**Comment by william-swl** [comment]
Thank you for the detailed description and long-standing support for `baizer`. 

However, I guess that this proposal should not be a feature of this package, but rather a function of a web crawling package or an image processing package. 

I will not add this function, but once again, thank you for your suggestion!
