### ISSUE TITLE
New Function Proposal: Count Unique Values from Variables in a Dataset

### ISSUE THREAD

**Issue by brichard1638** [william-swl/baizer#27]
There are innumerable ways in which to capture unique values from variables in a dataset or tibble. However, adding a function that not only captures this information in a succinct fashion after which the output is converted to a text file is not currently available within a function in R.

The code below can be used in a proposed new function that achieves the following tasks:
- First, the count of each unique value in all variables within a passed dataset is captured
- Finally, the output is converted to a user-selected file

The raw code used to generate this task in toto is provided below:
``
sink(paste0(path.expand("~"), "/unique_mbank.txt"), append = FALSE, split = FALSE)
``
``
library(dplyr)
``
``
apply(X = mbank, MARGIN = 2, FUN = unique) %>%
``
``
        lapply(FUN = length) %>%
``
``
        str()
``
``
sink()
``
``
closeAllConnections()
``

where mbank = a passed dataset

To view the output using the mbank dataset:
``
library(rbin)
``
``
data("mbank")
``

Output:

List of 17
 $ age           : int 67
 $ job            : int 12
 $ marital       : int 3
 $ education : int 4
 $ default      : int 2
 $ balance    : int 2312
 $ housing    : int 2
 $ loan          : int 2
 $ contact     : int 3
 $ day           : int 31
 $ month       : int 12
 $ duration    : int 865
 $ campaign : int 33
 $ pdays       : int 298
 $ previous   : int 20
 $ poutcome : int 4
 $ y               : int 2

Function Name, Construction, & Arguments:
- The proposed name of the function is, or could be **VarCountRpt**
- Functional configuration: **VarCountRpt(ds = "dataset name", fp = "mydocuments/varcntrep.txt")**

NOTE1: Perhaps additional information in the generated text file could be provided such as a formal name for the report, the dataset object name, the dimensions of the dataset used in the report, the date and time the report was generated, and a brief description. The object name, dimensions, the name of the report as well as cursory description could be added as arguments to the VarCountRpt function. Alternatively, a header consisting of the dataset object name, the object's dimensions, and the time and date of report creation could be combined into a single binary argument called **hdr**.

Extended Functional Configuration Example:
``
VarCountRpt(ds = "dataset name", fp = "mydocuments/varcntrep.txt", hdr = TRUE, rptname = "Secondary Report Provided to Finance", descr = "This report is provided to finance on a monthly basis on or about the end of the month.")
``

**Comment by william-swl** [comment]
Function `uniq_in_cols` has been added in `baizer v0.5.8`, which works like:
```
library(rbin)
data("mbank")

uniq_in_cols(mbank)
```
The result is a `tibble` object, you can write to your disk by `write_csv(res, 'file.csv')`.

Have fun:grinning:
